$(document).ready(function(){

    $(".emu").click(function(){
        $(".rui,.nene,.tsukasa").toggle(); 
        $(".emu-text").toggle();
        $(".emu-img").toggle();
    });

    $(".p1").click(function(){
        $("body").removeClass("mansionfront").addClass("mainhall")
        $(".p1").toggle();
        $(".p2").toggle();
    });
    $(".p2").click(function(){
        $(".p3").toggle();
        $(".p2").toggle();
    });
    $(".p3").click(function(){
        $(".p3").toggle();
        $(".p4").toggle();
    });
    $(".p4").click(function(){
        $(".p4").toggle();
        $(".p5").toggle();
    });
    $(".p5").click(function(){
        $(".p6").toggle();
        $(".p5").toggle();
    });
    $(".p6").click(function(){
        $(".pchoices").toggle();
    });
    $(".p7").click(function(){
        $(".pchoices").toggle();
        $(".p6").toggle();
        $(".p8").toggle();
    });
    $(".p8").click(function(){
        $(".pchoices").toggle();
        $(".p8").toggle();
    });
    $(".d1").click(function(){
        $(".d1").toggle();
        $(".d2").toggle();
    });
    $(".d2").click(function(){
        $(".d3").toggle();
        $(".d2").toggle();
    });
    $(".d3").click(function(){
        $(".d3").toggle();
        $(".d4").toggle();
        $(".dmap").toggle();
    });
    $(".d4").click(function(){
        $(".d4").toggle();
        $(".d5").toggle();
    });
    $(".d5").click(function(){
        $(".d6").toggle();
        $(".d5").toggle();
    });
    $(".d6").click(function(){
        $(".dchoices").toggle();
    });

    $(".e1").click(function(){
        $(".e1").toggle();
        $(".e2").toggle();
        $(".zombino").toggle();
    });
    $(".e2").click(function(){
        $(".e3").toggle();
        $(".e2").toggle();
        $(".zombino").toggle();
        $("body").addClass("tearoom")
    });
    $(".e3").click(function(){
        $(".e3").toggle();
        $(".e4").toggle();
    });
    $(".e4").click(function(){
        $(".e4").toggle();
        $(".e5").toggle();
        $(".jill").toggle();
    });
    $(".e5").click(function(){
        $(".echoices").toggle();
    });
    $(".f1").click(function(){
        $(".f1").toggle();
        $(".f2").toggle();
    });
    $(".f2").click(function(){
        $(".fchoices").toggle();
    });

    $(".ff1").click(function(){
        $(".fchoices").toggle();
        $(".f2").toggle();
        $(".f3").toggle();
    });

    $(".ff2").click(function(){
        $(".fchoices").toggle();
        $(".f2").toggle();
        $(".f4").toggle();
    });

    $(".f3").click(function(){
        $(".f3").toggle();
        $(".fchoices").toggle();
    });

    $(".f4").click(function(){
        $(".f4").toggle();
        $(".fchoices").toggle();
    });
    $(".yawn").ready(function(){
        $(".youaredead").fadeIn(8000);
    });

    $(".inventory").click(function(){
        $(".items").slideToggle();
    });
    $(".g1").click(function(){
        $(".g1").toggle();
        $(".g2").toggle();
    });

    $(".g2").click(function(){
        $(".fchoices").toggle();
    });
    $(".ff1").click(function(){
        $(".gchoices").toggle();
        $(".g2").toggle();
    });

    $(".gg2").click(function(){
        $(".jchoices").toggle();
        $(".i3").toggle();
        $(".f4").toggle();
    });
    $(".f4").click(function(){
        $(".f4").toggle();
        $(".jchoices").toggle();
    });
    $(".i1").click(function(){
        $(".i1").toggle();
        $(".i2").toggle();
    });
    $(".i2").click(function(){
        $(".i3").toggle();
        $(".i2").toggle();
    });
    $(".i3").click(function(){
        $(".jchoices").toggle();
    });
    $(".ii1").click(function(){
        $(".jchoices").toggle();
        $(".i4").toggle();
        $(".i3").toggle();
    });
    $(".i4").click(function(){
        $(".kchoices").toggle();
    });


    $(".q1").click(function(){
        $(".q1").toggle();
        $(".q2").toggle();
        $(".chris").toggle();
    });

    $(".q2").click(function(){
        $(".q3").toggle();
        $(".q2").toggle();
    });
    $(".q3").click(function(){
        $(".q3").toggle();
        $(".q4").toggle();
    });
    $(".q4").click(function(){
        $(".q4").toggle();
        $(".q5").toggle();
        $(".chris").toggle();
        $(".wesker").toggle();
    });
    $(".q5").click(function(){
        $(".q6").toggle();
        $(".q5").toggle();
    });
    
    $(".q6").click(function(){
        $(".q6").toggle();
        $(".q7").toggle();
    });

    $(".q7").click(function(){
        $(".q7").toggle();
        $(".q8").toggle();
    });
    $(".q8").click(function(){
        $(".q8").toggle();
        $(".q9").toggle();
    });
    
});